AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Breadcrumb

Globals:
  Function:
    Timeout: 10
    Runtime: provided.al2023
    MemorySize: 512
    Architectures: [arm64]
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersTable
        SEARCH_TABLE: !Ref SearchTable
        MEDIA_BUCKET: !Ref MediaBucket
        CLOUDFRONT_DISTRIBUTION_ID: !Ref CloudFrontDistribution
        CLOUDFRONT_DOMAIN: !GetAtt CloudFrontDistribution.DomainName
        QUEUE_URL: !GetAtt BreadQueue.QueueName
        CF_PRIVATE_KEY_SECRET_ARN: !Ref CloudFrontKeysSecret

Parameters:
  EnvironmentName:
    Type: String
    Description: "Environment name either production or test"
    Default: "test"

Resources:
  # auth
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-${EnvironmentName}-UserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: nickname
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: birthdate
          AttributeDataType: String
          Required: false
          Mutable: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${AWS::StackName}-${EnvironmentName}-Client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH

  CognitoCustomMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-${EnvironmentName}-CustomCognitoMessage
      MemorySize: 128
      CodeUri: bin/custom_email/custom_email.zip
      Handler: bootstrap
      Runtime: provided.al2023
      Description: Custom email logic for Cognito events
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: "*"
      Events:
        CognitoCustomMessageTrigger:
          Type: Cognito
          Properties:
            UserPool: !Ref CognitoUserPool
            Trigger: CustomMessage

  # api gateway
  BreadApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub ${AWS::StackName}-${EnvironmentName}-api
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - DELETE
          - PUT
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
      StageName: prod
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
              audience:
                - !Ref CognitoUserPoolClient
              claims:
                email_verified: "true"

  # bucket for media
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${EnvironmentName}-media-bucket-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - PUT
              - POST
              - GET
              - HEAD

            AllowedOrigins:
              - "*"

            AllowedHeaders:
              - "*"
            MaxAge: 3000 # for browser cache
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultiPartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-${EnvironmentName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt MediaBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TrustedKeyGroups:
            - !Ref CloudFrontKeyGroup
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  CloudFrontPublicKey:
    Type: AWS::CloudFront::PublicKey
    Properties:
      PublicKeyConfig:
        Name: !Sub "${AWS::StackName}-${EnvironmentName}-cf-public-key"
        CallerReference: !Sub "${AWS::StackName}-${EnvironmentName}-${AWS::Region}"
        EncodedKey: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuoOPR1FMvB5FX+eeYnqxK8+sTaNY6H64/6CcBNtqSwW7i27OufbMZmmcjSUkPMBLXR0BMEV9KJHGxt0uAeY4qbJNSc882+5Kx/6ZKlLBCGEXyhduQwnyWzFmPrL6rP9/Gf+PuJPNANWARgKSrVeENaoUOmYzSxdTNZZ3rgnyY5LPOzkhYSLQxcSCnhHL3d5XtdOIUP2HjmEbI+CdI0HEQ5sGk+DBxhwtSPRkDIREJqmhcy0lfQ8FZuFOsaf2lmETC1i2S4HlhCJXMRB60gquBeISYilv79Qej4z60VsrN32bAr3OFHB+QD81hyhmmiFeleaDupBwYJljn67A+xf9jQIDAQAB\n-----END PUBLIC KEY-----"

  CloudFrontKeyGroup:
    Type: AWS::CloudFront::KeyGroup
    Properties:
      KeyGroupConfig:
        Name: !Sub "${AWS::StackName}-${EnvironmentName}-cf-key-group"
        Items:
          - !Ref CloudFrontPublicKey

  MediaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MediaBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${MediaBucket.Arn}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
  
  CloudFrontKeysSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AWS::StackName}-${EnvironmentName}-cloudfront-keys"
      Description: "CloudFront private/public key pair for signed URLs"
      GenerateSecretString:
        SecretStringTemplate: '{"private_key":"","public_key":"","key_pair_id":""}'
        GenerateStringKey: "placeholder"

  PreSignUp:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-${EnvironmentName}-pre-signup-function"
      MemorySize: 128
      CodeUri: bin/signup_presignup/signup_presignup.zip
      Handler: bootstrap
      Description: Lambda function that runs before user signs up to validate user details
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        CognitoTrigger:
          Type: Cognito
          Properties:
            UserPool: !Ref CognitoUserPool
            Trigger: PreSignUp

  SignupUnfinishedRemover:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-${EnvironmentName}-remove-stale-accounts"
      MemorySize: 128
      CodeUri: bin/signup_unfinished_remover/signup_unfinished_remover.zip
      Handler: bootstrap
      Description: deletes unverified users from cognito when called
      Environment:
        Variables:
          USER_POOL_ID: !Ref CognitoUserPool
      Events:
        ScheduledRun:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)
            Name: DeleteUnconfirmedUsersSchedule
            Description: Runs every 12 hours, scans cognito users and deletes users with accounts older than 24 hours and are still unconfirmed
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminDeleteUser
            Resource: "*"

  MainHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-${EnvironmentName}-main-handler"
      CodeUri: bin/main_handler/main_handler.zip
      Handler: bootstrap
      Description: handle everything
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable 
          USER_POOL_ID: !Ref CognitoUserPool
          MEDIA_BUCKET: !Ref MediaBucket
          SECRETS_MANAGER_ARN: !Ref CloudFrontKeysSecret
          CLOUDFRONT_DISTRIBUTION_ID: !Ref CloudFrontDistribution
          CLOUDFRONT_DOMAIN: !GetAtt CloudFrontDistribution.DomainName
      Events:
        # for friends endpoints
        GetFriends:
          Type: HttpApi
          Properties:
            Path: /api/v1/friends/{id}
            Method: GET
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        GetCurrentUserFriends:
          Type: HttpApi
          Properties:
            Path: /api/v1/friends
            Method: GET
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        AcceptFriendRequest:
          Type: HttpApi
          Properties:
            Path: /api/v1/friends
            Method: POST
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        RemoveFriend:
          Type: HttpApi
          Properties:
            Path: /api/v1/friends/{id}
            Method: DELETE
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer

        #for friend requests
        GetFriendRequests:
          Type: HttpApi
          Properties:
            Path: /api/v1/friend-requests
            Method: GET
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        SendFriendRequests:
          Type: HttpApi
          Properties:
            Path: /api/v1/friend-requests
            Method: POST
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        RejectFriendRequests:
          Type: HttpApi
          Properties:
            Path: /api/v1/friend-requests/{id}
            Method: DELETE
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
    
        # for user stuff
        GetUser:
          Type: HttpApi
          Properties:
            Path: /api/v1/users/{id}
            Method: GET
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        CreateUser:
          Type: HttpApi
          Properties:
            Path: /api/v1/users
            Method: POST
            ApiId: !Ref BreadApi
        DeleteUser:
          Type: HttpApi
          Properties:
            Path: /api/v1/users/{id}
            Method: DELETE
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        EditUser:
          Type: HttpApi
          Properties:
            Path: /api/v1/users/{id}
            Method: PUT
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        AbortSignup:
          Type: HttpApi
          Properties:
            Path: /api/v1/signup/{id}
            Method: DELETE
            ApiId: !Ref BreadApi
      
        # for search
        SearchUser:
          Type: HttpApi
          Properties:
            Path: /api/v1/search/{str}
            Method: GET
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        NicknameAvailable:
          Type: HttpApi
          Properties:
            Path: /api/v1/search/{str}
            Method: POST
            ApiId: !Ref BreadApi
        
        # for crumbs stuff
        GetCrumbs:
          Type: HttpApi
          Properties:
            Path: /api/v1/crumbs
            Method: GET
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer

        GetCrumb:
          Type: HttpApi
          Properties:
            Path: /api/v1/crumbs/{id}
            Method: GET
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer

        ShareCrumb:
          Type: HttpApi
          Properties:
            Path: /api/v1/crumbs
            Method: POST
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer

        # for media access stuff
        MediaAccess:
          Type: HttpApi
          Properties:
            Path: /api/v1/media-access
            Method: POST
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        ChangeProfilePicture:
          Type: HttpApi
          Properties:
            Path: /api/v1/profile-picture
            Method: PUT
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer
        GetProfilePicture:
          Type: HttpApi
          Properties:
            Path: /api/v1/profile-picture
            Method: GET
            ApiId: !Ref BreadApi
            Auth:
              Authorizer: CognitoAuthorizer

      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub "${MediaBucket.Arn}/*"
        - Statement:
            Effect: Allow
            Action:
              - s3:DeleteObject
            Resource: !Sub "${MediaBucket.Arn}/*"
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Ref CloudFrontKeysSecret
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SearchTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt BreadQueue.QueueName
        - Statement:
            Effect: Allow
            Action:
              - cognito-idp:AdminDeleteUser
              - cognito-idp:AdminGetUser
              - cognito-idp:AdminUserGlobalSignOut
            Resource: "*"

  ProcessMediaUploads:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-${EnvironmentName}-process-media-upload"
      CodeUri: bin/process_upload/process_upload.zip
      Handler: bootstrap
      Description: Triggered when a file upload completes in the media bucket
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          MEDIA_BUCKET: !Ref MediaBucket
      Events:
        S3Upload:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - "Object Created"
              detail:
                bucket:
                  name:
                    - !Ref MediaBucket
                object:
                  key:
                    - prefix: "uploads/"
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref MediaBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-${EnvironmentName}-Main-Table"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi
          AttributeType: S
        - AttributeName: gsiSk
          AttributeType: S
        - AttributeName: gsi2
          AttributeType: S
        - AttributeName: gsi2Sk
          AttributeType: S
        - AttributeName: gsi3
          AttributeType: S
        - AttributeName: gsi3Sk
          AttributeType: S
        - AttributeName: gsi4
          AttributeType: S
        - AttributeName: gsi4Sk
          AttributeType: S
        - AttributeName: gsi5
          AttributeType: S
        - AttributeName: gsi5Sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSIndex
          KeySchema:
            - AttributeName: gsi
              KeyType: HASH
            - AttributeName: gsiSk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSIndex2
          KeySchema:
            - AttributeName: gsi2
              KeyType: HASH
            - AttributeName: gsi2Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSIndex3
          KeySchema:
            - AttributeName: gsi3
              KeyType: HASH
            - AttributeName: gsi3Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSIndex4
          KeySchema:
            - AttributeName: gsi4
              KeyType: HASH
            - AttributeName: gsi4Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSIndex5
          KeySchema:
            - AttributeName: gsi5
              KeyType: HASH
            - AttributeName: gsi5Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        
  SearchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-${EnvironmentName}-search"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  QueueActions:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-bread-queue-actions-${EnvironmentName}
      CodeUri: bin/queue_actions/queue_actions.zip
      Handler: bootstrap
      Description: function to handle stuff in queue
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - SQSPollerPolicy:
            QueueName: !GetAtt BreadQueue.QueueName
      Events:
        BreadQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BreadQueue.Arn

  BreadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-bread-queue-${EnvironmentName}
      MessageRetentionPeriod: 86400
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt BreadDeadLetterQueue.Arn
        maxReceiveCount: 3

  BreadDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-bread-dlq-${EnvironmentName}

Outputs:
  BreadApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${BreadApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  CognitoUserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPool
  CognitoUserPoolClientId:
    Description: "Cognito App Client ID"
    Value: !Ref CognitoUserPoolClient
