package constants

// set to false to enforce hard ban
var BannedTerms = map[string]bool{
	// "69":                          false,
	"2g1c":                        false,
	"2 girls 1 cup":               false,
	"acrotomophilia":              false,
	"alabama hot pocket":          false,
	"alaskan pipeline":            false,
	"anal":                        false,
	"anilingus":                   false,
	"anus":                        false,
	"apeshit":                     false,
	"arsehole":                    false,
	"ass":                         false,
	"asshole":                     false,
	"assmunch":                    false,
	"auto erotic":                 false,
	"autoerotic":                  false,
	"babeland":                    false,
	"baby batter":                 false,
	"baby juice":                  false,
	"ball gag":                    false,
	"ball gravy":                  false,
	"ball kicking":                false,
	"ball licking":                false,
	"ball sack":                   false,
	"ball sucking":                false,
	"bangbros":                    false,
	"bangbus":                     false,
	"bareback":                    false,
	"barenaked":                   false,
	"bastard":                     false,
	"bastardo":                    false,
	"bastinado":                   false,
	"bbw":                         false,
	"bdsm":                        false,
	"beaner":                      false,
	"beaners":                     false,
	"beaver cleaver":              false,
	"beaver lips":                 false,
	"beastiality":                 false,
	"bestiality":                  false,
	"big black":                   false,
	"big breasts":                 false,
	"big knockers":                false,
	"big tits":                    false,
	"bimbos":                      false,
	"birdlock":                    false,
	"bitch":                       false,
	"bitches":                     false,
	"black cock":                  false,
	"blonde action":               false,
	"blonde on blonde action":     false,
	"blowjob":                     false,
	"blow job":                    false,
	"blow your load":              false,
	"blue waffle":                 false,
	"blumpkin":                    false,
	"bollocks":                    false,
	"bondage":                     false,
	"boner":                       false,
	"boob":                        true,
	"boobs":                       true,
	"booty call":                  false,
	"brown showers":               false,
	"brunette action":             false,
	"bukkake":                     false,
	"bulldyke":                    false,
	"bullet vibe":                 false,
	"bullshit":                    false,
	"bung hole":                   false,
	"bunghole":                    false,
	"busty":                       false,
	"butt":                        false,
	"buttcheeks":                  false,
	"butthole":                    false,
	"chink":                       false,
	"camel toe":                   false,
	"camgirl":                     false,
	"camslut":                     false,
	"camwhore":                    false,
	"carpet muncher":              false,
	"carpetmuncher":               false,
	"chocolate rosebuds":          false,
	"cialis":                      false,
	"circlejerk":                  false,
	"cleveland steamer":           false,
	"clit":                        false,
	"clitoris":                    false,
	"clover clamps":               false,
	"clusterfuck":                 false,
	"cock":                        false,
	"cocks":                       false,
	"coprolagnia":                 false,
	"coprophilia":                 false,
	"cornhole":                    false,
	"coon":                        false,
	"coons":                       false,
	"creampie":                    false,
	"cum":                         false,
	"cumming":                     false,
	"cumshot":                     false,
	"cumshots":                    false,
	"cunnilingus":                 false,
	"cunt":                        false,
	"darkie":                      false,
	"date rape":                   false,
	"daterape":                    false,
	"deep throat":                 false,
	"deepthroat":                  false,
	"dendrophilia":                false,
	"dick":                        false,
	"dildo":                       false,
	"dingleberry":                 false,
	"dingleberries":               false,
	"dirty pillows":               false,
	"dirty sanchez":               false,
	"doggie style":                false,
	"doggiestyle":                 false,
	"doggy style":                 false,
	"doggystyle":                  false,
	"dog style":                   false,
	"dolcett":                     false,
	"domination":                  false,
	"dominatrix":                  false,
	"dommes":                      false,
	"donkey punch":                false,
	"double dong":                 false,
	"double penetration":          false,
	"dp action":                   false,
	"dry hump":                    false,
	"dvda":                        false,
	"eat my ass":                  false,
	"ecchi":                       false,
	"ejaculation":                 false,
	"erotic":                      false,
	"erotism":                     false,
	"escort":                      false,
	"eunuch":                      false,
	"fag":                         false,
	"faggot":                      false,
	"fecal":                       false,
	"felch":                       false,
	"fellatio":                    false,
	"feltch":                      false,
	"female squirting":            false,
	"femdom":                      false,
	"figging":                     false,
	"fingerbang":                  false,
	"fingering":                   false,
	"fisting":                     false,
	"foot fetish":                 false,
	"footjob":                     false,
	"frotting":                    false,
	"fuck":                        true,
	"fuck buttons":                false,
	"fuckin":                      false,
	"fucking":                     false,
	"fucktards":                   false,
	"fudge packer":                false,
	"fudgepacker":                 false,
	"futanari":                    false,
	"gangbang":                    false,
	"gang bang":                   false,
	"gay sex":                     false,
	"genitals":                    false,
	"giant cock":                  false,
	"girl on":                     false,
	"girl on top":                 false,
	"girls gone wild":             false,
	"goatcx":                      false,
	"goatse":                      false,
	"god damn":                    false,
	"gokkun":                      false,
	"golden shower":               false,
	"goodpoop":                    false,
	"goo girl":                    false,
	"goregasm":                    false,
	"grope":                       false,
	"group sex":                   false,
	"g-spot":                      false,
	"guro":                        false,
	"hand job":                    false,
	"handjob":                     false,
	"hard core":                   false,
	"hardcore":                    false,
	"hentai":                      false,
	"homoerotic":                  false,
	"honkey":                      false,
	"hooker":                      false,
	"horny":                       false,
	"hot carl":                    false,
	"hot chick":                   false,
	"how to kill":                 false,
	"how to murder":               false,
	"huge fat":                    false,
	"humping":                     false,
	"incest":                      false,
	"intercourse":                 false,
	"jack off":                    false,
	"jelly donut":                 false,
	"jerk off":                    false,
	"jigaboo":                     false,
	"jiggaboo":                    false,
	"jiggerboo":                   false,
	"jizz":                        false,
	"juggs":                       false,
	"kike":                        false,
	"kinbaku":                     false,
	"kinkster":                    false,
	"kinky":                       false,
	"knobbing":                    false,
	"leather restraint":           false,
	"leather straight jacket":     false,
	"lemon party":                 false,
	"livesex":                     false,
	"lovemaking":                  false,
	"make me come":                false,
	"male squirting":              false,
	"masturbate":                  false,
	"masturbating":                false,
	"masturbation":                false,
	"menage a trois":              false,
	"milf":                        false,
	"missionary position":         false,
	"mong":                        false,
	"motherfucker":                false,
	"mound of venus":              false,
	"mr hands":                    false,
	"muff diver":                  false,
	"muffdiving":                  false,
	"nambla":                      false,
	"nawashi":                     false,
	"negro":                       false,
	"neonazi":                     false,
	"nigga":                       true,
	"nigger":                      true,
	"nig nog":                     false,
	"nimphomania":                 false,
	"nipple":                      false,
	"nipples":                     false,
	"nsfw":                        false,
	"nsfw images":                 false,
	"nude":                        false,
	"nudity":                      false,
	"nut":                         false,
	"nutten":                      false,
	"nympho":                      false,
	"nymphomania":                 false,
	"octopussy":                   false,
	"omorashi":                    false,
	"one cup two girls":           false,
	"one guy one jar":             false,
	"orgasm":                      false,
	"orgy":                        false,
	"paki":                        false,
	"panties":                     false,
	"panty":                       false,
	"pegging":                     false,
	"penis":                       false,
	"phone sex":                   false,
	"piece of shit":               false,
	"pikey":                       false,
	"pissing":                     false,
	"piss pig":                    false,
	"pisspig":                     false,
	"pleasure chest":              false,
	"pole smoker":                 false,
	"ponyplay":                    false,
	"poof":                        false,
	"poon":                        false,
	"poontang":                    false,
	"punany":                      false,
	"poop chute":                  false,
	"poopchute":                   false,
	"porn":                        false,
	"porno":                       false,
	"pornography":                 false,
	"prince albert piercing":      false,
	"pthc":                        false,
	"pubes":                       false,
	"pussy":                       false,
	"queaf":                       false,
	"queef":                       false,
	"quim":                        false,
	"raghead":                     false,
	"raging boner":                false,
	"rape":                        false,
	"raper":                       false,
	"raping":                      false,
	"rapist":                      false,
	"rectum":                      false,
	"reverse cowgirl":             false,
	"rimjob":                      false,
	"rimming":                     false,
	"rosy palm":                   false,
	"rosy palm and her 5 sisters": false,
	"rusty trombone":              false,
	"sadism":                      false,
	"santorum":                    false,
	"scat":                        false,
	"schlong":                     false,
	"scissoring":                  false,
	"semen":                       false,
	"sex":                         false,
	"sexcam":                      false,
	"sexo":                        false,
	"sexy":                        false,
	"sexual":                      false,
	"sexually":                    false,
	"sexuality":                   false,
	"shaved beaver":               false,
	"shaved pussy":                false,
	"shemale":                     false,
	"shibari":                     false,
	"shit":                        false,
	"shitblimp":                   false,
	"shitty":                      false,
	"shrimping":                   false,
	"skeet":                       false,
	"slanteye":                    false,
	"slut":                        false,
	"s&m":                         false,
	"smut":                        false,
	"snatch":                      false,
	"snowballing":                 false,
	"sodomize":                    false,
	"sodomy":                      false,
	"spastic":                     false,
	"spic":                        false,
	"splooge":                     false,
	"splooge moose":               false,
	"spooge":                      false,
	"spread legs":                 false,
	"spunk":                       false,
	"strap on":                    false,
	"strapon":                     false,
	"strappado":                   false,
	"strip club":                  false,
	"style doggy":                 false,
	"suck":                        false,
	"suicide":                     false,
	"suicide girls":               false,
	"sultry women":                false,
	"swastika":                    false,
	"swinger":                     false,
	"tainted love":                false,
	"taste my":                    false,
	"tea bagging":                 false,
	"threesome":                   false,
	"throating":                   false,
	"thumbzilla":                  false,
	"tied up":                     false,
	"tight white":                 false,
	"tit":                         false,
	"tits":                        false,
	"titties":                     false,
	"titty":                       false,
	"tongue in a":                 false,
	"topless":                     false,
	"tosser":                      false,
	"towelhead":                   false,
	"tranny":                      false,
	"tribadism":                   false,
	"tub girl":                    false,
	"tubgirl":                     false,
	"tushy":                       false,
	"twat":                        false,
	"twink":                       false,
	"twinkie":                     false,
	"two girls one cup":           false,
	"undressing":                  false,
	"upskirt":                     false,
	"urethra play":                false,
	"urophilia":                   false,
	"vagina":                      false,
	"venus mound":                 false,
	"viagra":                      false,
	"vibrator":                    false,
	"violet wand":                 false,
	"vorarephilia":                false,
	"voyeur":                      false,
	"voyeurweb":                   false,
	"voyuer":                      false,
	"vulva":                       false,
	"wank":                        false,
	"wetback":                     false,
	"wet dream":                   false,
	"white power":                 false,
	"whore":                       false,
	"worldsex":                    false,
	"wrapping men":                false,
	"wrinkled starfish":           false,
	"xx":                          false,
	"xxx":                         false,
	"yaoi":                        false,
	"yellow showers":              false,
	"yiffy":                       false,
	"zoophilia":                   false,
	"hitler":                      false,
	"booty":                       false,
	"nazi":                        false,
	"hate":                        false,
	"jihad":                       false,
	"terrorist":                   false,
	"breadcrumb":                  false,
	"pedo":                        false,
	"peado":                       false,
	"touching":                    false,
	"pedophile":                   false,
	"bunda":                       false,
	"bunnda":                      false,
}
